# Generated by Django 2.2.22 on 2021-05-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Humiture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_number', models.CharField(blank=True, max_length=255)),
                ('upload_time', models.DateTimeField(blank=True)),
                ('temperature', models.IntegerField(blank=True)),
                ('humidity', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'humiture',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(blank=True, max_length=255)),
                ('site', models.CharField(blank=True, max_length=255)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('upload_time', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'picture',
            },
        ),
        migrations.CreateModel(
            name='Tev',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_number', models.CharField(blank=True, max_length=255)),
                ('upload_time', models.DateTimeField(blank=True)),
                ('max', models.FloatField(blank=True)),
                ('average', models.FloatField(blank=True)),
                ('pulse', models.FloatField(blank=True)),
                ('electric', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'tev',
            },
        ),
    ]
